version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1212
      MYSQL_DATABASE: votingsystem
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1212
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  webserver:
    image: php:8.0-apache
    container_name: apache_php_container
    volumes:
      - ./votesystem:/var/www/html  # Código fuente local que se montará en el contenedor
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge